# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


flutter_application_path = '../flutter_nettruyen'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'NettruyenIOS' do


  use_frameworks!
  install_all_flutter_pods(flutter_application_path)





  target 'NettruyenIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NettruyenIOSUITests' do
    # Pods for testing
  end

end
